### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by shackra** [ktrysmt/go-bitbucket#11]
I did a fork of this project and I was wondering which license are you using, I used [swagger](https://github.com/swagger-api/swagger-codegen) to generated all data structures from [Bitbucket swagger definition](https://api.bitbucket.org/swagger.json) and the generated code is under the Apache License 2.0 so hopefully your license is compatible with it.

I'm thinking on licensing my changes to LGPL v3.

**Comment by ktrysmt** [comment]
Thank you for your info. I will change the license from MIT to Apache 2.0 more stringent.

**Comment by ktrysmt** [comment]
Done.
