### ISSUE TITLE
Invalid type assertion issues for Branch Restrict Tests

### ISSUE THREAD

**Issue by DataDavD** [ktrysmt/go-bitbucket#144]
When trying to test the repo received this error (two times) failing the test build
`invalid type assertion: res.(map[string]<inter>) (non-interface type *bitbucket.BranchRestrictions on left`

It appears to be caused by changing the return type of `BranchRestrictions.Create()` method; completed during this [PR merge](https://github.com/ktrysmt/go-bitbucket/pull/129/files). It was interface{} before whereas now its `*BranchRestrictions` so the type assertion during the BranchRestrictionsTests causes the test build to fail. 

Specifically, now the issue is caused by [this line](https://github.com/ktrysmt/go-bitbucket/blob/master/tests/branchrestrictions_test.go#L75) and [this line](https://github.com/ktrysmt/go-bitbucket/blob/master/tests/branchrestrictions_test.go#L47)

I can try and fix this after I complete my DiffStat PR if thats fine. Is that cool if I take this bug-fix over?

Also, can I ignore this type assertion issue when testing and submitting my [DiffStat PR](https://github.com/ktrysmt/go-bitbucket/issues/142) ? 

Thanks again!!!!

**Comment by ktrysmt** [comment]
I see. I think that's better idea.
I'll review the DiffStat PR. @DataDavD

**Comment by ktrysmt** [comment]
Thank you for your analysis and consideration. And I'm grad if you do it. @DataDavD

**Comment by DataDavD** [comment]
Great I will definitely work on this. I also made another issue/thread about a similar thing. I intend to work on that as part of this work as well.

Also, for clarity, I intend to contribute much more to this great project. Happy to help anywhere you need help. I would love to help mock up the API response for tests so that the testing is more robust. Also happy to help with improved response decoding and GitHub actions CI.

Last, I am a bit confused about the test environment for master/develop. That was the one part I am still a bit confused on and once I have more clarity I should be able to write tests better, along with mocks, as well as improving response decoding, etc.

Happy coding @ktrysmt !!!!!!!!

**Comment by oogali** [comment]
Created PR #147 to resolve this issue and resolve the failing tests.
