### ISSUE TITLE
Panic for Create BranchRestrictions.

### ISSUE THREAD

**Issue by craigmonson** [ktrysmt/go-bitbucket#15]
Don't have time to log a PR at the moment, but figured I'd log it just in case I can't get to it:

Running a create on branch restrictions, where the user or group is empty causes the server to respond with a bad request "users malformed".  It's because it's expecting a list, not a key-value hash.  However, when I add an empty user it panics.  I was able to get around this by applying the diff below, and leaving users and groups blank (which defaults to "everyone", which is what I wanted).  I didn't have time to check if it still fired off a panic with this change though.

```patch
diff --git a/branchrestrictions.go b/branchrestrictions.go
index 6c696a1..31e6865 100644
--- a/branchrestrictions.go
+++ b/branchrestrictions.go
@@ -40,8 +40,8 @@ func (b *BranchRestrictions) Delete(bo *BranchRestrictionsOptions) interface{} {
 func (b *BranchRestrictions) buildBranchRestrictionsBody(bo *BranchRestrictionsOptions) string {

        body := map[string]interface{}{}
-       body["groups"] = map[string]string{}
-       body["users"] = map[string]string{}
+       body["groups"] = []map[string]string{}
+       body["users"] = []map[string]string{}

        if bo.Pattern != "" {
                body["pattern"] = bo.Pattern
```

**Comment by ktrysmt** [comment]
Thank you for your patch, I will check and then add a test for that.

**Comment by ktrysmt** [comment]
@craigmonson, I did fix the bug. Please check that behavior.
Also I putout the testcode about branchrestrictions, refer to it. 
https://github.com/ktrysmt/go-bitbucket/blob/master/tests/branchrestrictions_test.go
