### ISSUE TITLE
Creating repository example

### ISSUE THREAD

**Issue by isindir** [ktrysmt/go-bitbucket#160]
Hi @ktrysmt ,

I need to create a repository, I find it difficult to understand how to do that with provided library.

I can authenticate, then I can list repositories, but in order to create repository I need to use another repository object which has `c` member as `*Client`. If I don't have any repositories in account - how can I create one ? Also, as `Repository.c` is not exported I can't create `Repository` object and set `c` after authentication function call. Looking at the interfaces it seems that all of the types suffer the same issue and only type which can create other type is `Workspace`. Could you please provide working example on how to create repository or if that is not possible add `Client` setter member function to all types ? Or maybe `Client` must have `CreateRepository` ?

I'm trying to do approx following right now:

```go
	username, usernameFound := os.LookupEnv("BITBUCKET_USERNAME")
	if !usernameFound {
		fmt.Println("Error: environment variable BITBUCKET_USERNAME not found")
		os.Exit(1)
	}

	token, tokenFound := os.LookupEnv("BITBUCKET_TOKEN")
	if !tokenFound {
		fmt.Println("Error: environment variable BITBUCKET_TOKEN not found")
		os.Exit(1)
	}

	client := bitbucket.NewBasicAuth(username, token)

        r := &bitbucket.Repository{}

        ro := &bitbucket.RepositoryOptions{
		Owner: owner,
		RepoSlug: repository,
	}

        resultingRepository, err := r.Create(ro)
```

**Comment by ktrysmt** [comment]
Hmm, I'lll check and consider about it. Thanks @isindir

**Comment by ktrysmt** [comment]
Example is there.

```
package main

import (
        "fmt"
        "github.com/ktrysmt/go-bitbucket"
)

func main() {
        c := bitbucket.NewBasicAuth("username", "password")

        opt := &bitbucket.RepositoryOptions{
                Owner:    "project_name",
                RepoSlug: "repo_name",
                Scm:      "git",
        }

        res, err := c.Repositories.Repository.Create(opt)
        if err != nil {
                panic(err)
        }

        fmt.Println(res)
}
```
The structure with repositories in repositories may be a little confusing. In the old api specifications, the operation of a repository was defined under repositories. So I fixed the struct structure according to the api structure. 

And then, is it unified with repositories / {project} / {repo} now? It seems.

**Comment by isindir** [comment]
@ktrysmt Thank you for explanation. I see now, I didn't found that passtrough and it feels bit different from typical golang libraries. Gitlab and github for example are more or less centric around client object. May be it's worth mentioning this example in a readme as it is the only documentation available as well. Closing this issue.

**Comment by ktrysmt** [comment]
@isindir  You're right. However, if we suddenly change the behavior of the client, it will have a big impact on some users, so I would like to think a little about how to solve it. For the time being, I will write it in the readme. Thank you.
