### ISSUE TITLE
Add DiffStat functionality to remove certain fields from response

### ISSUE THREAD

**Issue by DataDavD** [ktrysmt/go-bitbucket#166]
With a recent change to the API, you can now remove certain response fields from the DiffStat API. For example you can include the query parameters: `?fields=-values.lines_added,-values.lines_removed` to remove those fields the API returns. 

It would be nice to have this functionality added to the `DiffStat` method.

@ktrysmt can you please assign this issue to me. I have already started working on this; I should have the PR ready in less than a week.

Thank you.

**Comment by ktrysmt** [comment]
Good information. I agreed it.

Thank you @DataDavD
