### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by tzaffi** [ktrysmt/go-bitbucket#17]
The bitbucket API provides paginated output but this repo doesn't handle it. Consequently, result sets are limited to the first page only and for large responses the result set is incomplete.

In particular, the parser will need to handle the following values in the bitbucket's JSON response:

* next
* page
* pagelen
* previous

**Comment by ktrysmt** [comment]
Bitbucket API alway returns these pagination datas as JSON response, I understand.
But to be sure, Request creation functions does not have logics to manage paginations.
I will try implement it, also write tests to guarantee it.

**Comment by tzaffi** [comment]
Thanks! I may also try to do my bit. If I make progress I will make a pull request.

**Comment by mainiak** [comment]
Hello.

Please see my crude implementation of pagination in pull request #22
