### ISSUE TITLE
Creating a Repo in bitbucket cloud fails with 400 code 

### ISSUE THREAD

**Issue by zaalgol** [ktrysmt/go-bitbucket#173]
I am using github.com/ktrysmt/go-bitbucket pkg for creating a repo in our bitbucket cloud.

Getting an existing repo works OK:

```
c := bitbucket.NewBasicAuth(name, password)
opt = &bitbucket.RepositoryOptions{
    Owner:    <owner name>,
    // Project:  "devops-utils", //not mandatoty
    RepoSlug: <exist-repo-slug>,
    Scm:      "git",
}
res, err := c.Repositories.Repository.Get(opt)
```

But creating a new one just returns 400 - Bad request, with no more details.
```

c := bitbucket.NewBasicAuth(name, password)
opt := &bitbucket.RepositoryOptions {
    Owner:    <owner name>,
    Project:  "devops-utils",
    RepoSlug: <new-repo-slug>,
    Scm:      "git",
} 
_, err := c.Repositories.Repository.Create(opt)
```

**Comment by ktrysmt** [comment]
Thank you for your report. I will check it.

**Comment by ktrysmt** [comment]
Hi, @zaalgol 

### 1. Permission

Did you create app-password or api-token with adding permisison of "project"?
400 is defined that "or if the caller lacks the privilege to create repositories under the targeted account" by them.

### Inbalid body

Perhaps your project key is invalid. 
Project key is required only uppercase letters and numbers with fewer characters, no symbols included.
You can know easily a validation of keyname here; 
* https://bitbucket.org/account/projects/create
* https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D#post

### Project publishing
Private project key is invalid but public project key is valid in this api. But I don't know that reason...
