### ISSUE TITLE
Question about Client.Auth

### ISSUE THREAD

**Issue by moose56** [ktrysmt/go-bitbucket#189]
Hi, is there any way to access the Client.Auth values?

I want to use the token to create a url to clone a repository using an access token as described [here](https://developer.atlassian.com/cloud/bitbucket/rest/intro/#repository-cloning). But there does not appear to be any way of accessing the token value.

Am I missing something obvious, or is this just not possible?

**Comment by ktrysmt** [comment]
@moose56 
If you already have the token, you may be able to use bashAuth.
```
c := new NewBasicAuth{"x-token-auth", token}
```

**Comment by ktrysmt** [comment]
@moose56  You may be able to use it;
```
c := new NewOAuthClientCredentials("id","secret")
fmt.Println(c.Auth.token)
```

**Comment by moose56** [comment]
@ktrysmt that is ideally what I want to do but token is not public. 
 
Is a specific decision to never expose it to users of the Client or could access to this property (and other auth properties) be added in the future?

**Comment by ktrysmt** [comment]
Oh that's right, the field is private. It would be good to implement a getter or a public field.

**Comment by ktrysmt** [comment]
@moose56  I wrote a getter to extract the token struct as a trial, so please try to see if it meets your expectations.
https://github.com/ktrysmt/go-bitbucket/pull/190/commits/490ee37c481f10540018f1fcfcdfeacbc950a4a5

**Comment by moose56** [comment]
Hi, that is exactly what I needed. Thank you for even creating the pull request for me!
