### ISSUE TITLE
Support Commit Statuses

### ISSUE THREAD

**Issue by josead** [ktrysmt/go-bitbucket#19]
Hello guys,
I found that Commits.go has not support for the following API endpoint...
I wander if this issue can be addressed.

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/commit/%7Bnode%7D/statuses

I can provide a PR for this, but I'd wait for you guys to accept it :)
BTW: This would be my first contribution to open source community

**Comment by ktrysmt** [comment]
Thank you for your contrib.
I will check it.
