### ISSUE TITLE
error: unsupported protocol scheme for Pipelines.List(opt)

### ISSUE THREAD

**Issue by hkailantzis** [ktrysmt/go-bitbucket#198]
Hi there,

Thanks very much for the repo. I'm relatively new to GoLang, and wondering what could be the problem when trying to list the pipelines for a repo. _PullRequests.Gets()_ methods or _Repository.GetFileBlob_ works fine for me. So, I'm wondering if something else missing with the URL bit of _Pipelines.list()_ call: -> 

https://github.com/ktrysmt/go-bitbucket/blob/master/pipelines.go#L14

Error I'm getting is: **unsupported protocol scheme** .  I just noticed that _PullRequests.Gets_ method is using: p.c.GetApiBaseURL(), which is missing from the Pipelines.list() call. Could that be causing the issue ?

https://github.com/ktrysmt/go-bitbucket/blob/master/pullrequests.go#L31

```
func getPipelinesTest() {
	
	c := bitbucket.NewBasicAuth("username", "password")

	opt := &bitbucket.PipelinesOptions{
		Owner:    "owner",
		RepoSlug: "test_project",
	}

	res, err := c.Repositories.Pipelines.List(opt)
	if err != nil {
		panic(err)
	}

	log.Println(res)
}
```

**Comment by ktrysmt** [comment]
Hmm, I'll check it out. Thank you for the report.

**Comment by hkailantzis** [comment]
Thanks @ktrysmt, that's great.

**Comment by hkailantzis** [comment]
@ktrysmt, any info/feedback if its possible to fix this ? Thanks in advance!

**Comment by Jamess-Lucass** [comment]
@hkailantzis I know this is an old issue but the method is `.Gets()` and not `.List()`

I am using [v0.9.54](https://github.com/ktrysmt/go-bitbucket/releases/tag/v0.9.54)

The following code works for me:
```go
b := bitbucket.NewBasicAuth(username, password)

opts := &bitbucket.PullRequestsOptions{
        Owner:		"owner",
        RepoSlug: 	"repo",
}

response, err := b.Repositories.PullRequests.Gets(opts)
```

**Comment by Jamess-Lucass** [comment]
@hkailantzis I am aware this is an old issue but are you still able to replicate the issue?

I am on using version [v0.9.54](https://github.com/ktrysmt/go-bitbucket/releases/tag/v0.9.54) and I am unable to replicate

**Comment by hkailantzis** [comment]
@Jamess-Lucass , is working it seems now, not sure what was the problem. closing this, thanks!
