### ISSUE TITLE
Support OAuth 2.0

### ISSUE THREAD

**Issue by mainiak** [ktrysmt/go-bitbucket#21]
Despite there is [bitbucket.NewOAuth()](https://godoc.org/github.com/ktrysmt/go-bitbucket#NewOAuth) method, it is NOT actually implemented.

Specification can be found [here](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html)

**Comment by ktrysmt** [comment]
That's right. 
I will make it while reading the spec.

**Comment by brunomdev** [comment]
+1

**Comment by srgrn** [comment]
in #31 i have added a simple offline oauth2 implementation

**Comment by ktrysmt** [comment]
Thank you for your contribution! I will review it.
