### ISSUE TITLE
Add support for managing user & group permissions on repositories

### ISSUE THREAD

**Issue by zahiar** [ktrysmt/go-bitbucket#213]
Bitbucket has released (back in May 2022) new Bitbucket Cloud 2.0 API endpoints for managing users and groups permissions on repositories. 

Blog article here: https://developer.atlassian.com/cloud/bitbucket/new-repo-permission-apis/

Be great if we could get this implemented & no more having to deal with version 1.0 of their API 🙌

**Comment by ferrandinand** [comment]
I have just created a PR in order to include this feature, let's see if it is all fine
