### ISSUE TITLE
Try generate api client from bitbucket api by swagger ...

### ISSUE THREAD

**Issue by ktrysmt** [ktrysmt/go-bitbucket#24]
> I wish I got api client automatically.
> But I still, failed.

## Install swagger

```
go get -u github.com/go-swagger/go-swagger/cmd/swagger
```

## Try it

```
swagger validate https://api.bitbucket.org/swagger.json
wget https://api.bitbucket.org/swagger.json
swagger generate client -f ./swagger.json -A api
```

## Log

```
$ swagger validate https://api.bitbucket.org/swagger.json
The swagger spec at "https://api.bitbucket.org/swagger.json" is invalid against swagger specification 2.0. see errors :
- definition "pipeline_selector" contains duplicate properties: [pipeline_selector.type]
- duplicate parameter name "files" for "query" in operation ""
- path param "{schedule_uuid}" has no parameter definition
- path param "pull_request_id" is not present in path "/repositories/{username}/{repo_slug}/pullrequests/activity"
```

Oops,

```
$ wget https://api.bitbucket.org/swagger.json
$ swagger generate client -f ./swagger.json -A api
The swagger spec at "./swagger.json" is invalid against swagger specification 2.0. see errors :
- definition "pipeline_selector" contains duplicate properties: [pipeline_selector.type]
- path param "pull_request_id" is not present in path "/repositories/{username}/{repo_slug}/pullrequests/activity"
- path param "{schedule_uuid}" has no parameter definition
- duplicate parameter name "files" for "query" in operation ""
```

Also generate client was failed.

Seems that have to fix some errors, but the json content is so huge(473kb).

**Comment by ktrysmt** [comment]
swagger.json is [here](https://api.bitbucket.org/swagger.json)

**Comment by srgrn** [comment]
see https://github.com/srgrn/bitbucket-api
I was able to use swagger-codegen after removing 3 lines relating to:

> /repositories/{username}/{repo_slug}/properties/{app_key}/{property_name}

it can be seen that it is not the most comfortable client, however it does seem to work.

**Comment by ktrysmt** [comment]
You are right, it is not confortable... 
It took me a while to understand. But it seems to be usable. Thank you.

**Comment by ktrysmt** [comment]
And then it is not to need remove lines from source,
> /repositories/{username}/{repo_slug}/properties/{app_key}/{property_name}
swagger-codegen 2.3.1 generated codes that seemed correct.

**Comment by ktrysmt** [comment]
It is old topics. I checked it again and there were occourred errors more and more..
https://github.com/ktrysmt/go-bitbucket/issues/96
