### ISSUE TITLE
Doesn't support self hosted instances

### ISSUE THREAD

**Issue by ezhil56x** [ktrysmt/go-bitbucket#287]
Does `go-bitbucket` support self hosted bitbucket instances? Because the api url for self hosted and bitbucket hosted instance are different. I could see SetApiBaseURL and tried using it couldn't make it to work. If `go-bitbucket` supports self hosted instance, it would be great if you could give an example how to use it
Thanks!

**Comment by ktrysmt** [comment]
Hi @ezhil56x, sorry to late and did you read FAQs?
https://github.com/ktrysmt/go-bitbucket?tab=readme-ov-file#support-bitbucket-api-v10-

If the specifications haven't changed since the past, the api version may be 1.0, so check it out.
