### ISSUE TITLE
diff api response is not json

### ISSUE THREAD

**Issue by zenixls2** [ktrysmt/go-bitbucket#29]
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/diff/%7Bspec%7D

if the statusCode == 200, you should treat it as plain text, not json.
otherwise
https://github.com/ktrysmt/go-bitbucket/blob/master/client.go#L110
would return error, and cause the function fail.
(you might have to do some check on the resBodyBytes that it starts with `"` or `{`)

**Comment by ktrysmt** [comment]
Thank you for your report. I will fix it.
