### ISSUE TITLE
Add pullrequest state at the option

### ISSUE THREAD

**Issue by ktrysmt** [ktrysmt/go-bitbucket#38]
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests#get

## Query parameters
|Name	|Type	|Description|
| --- | --- | --- |
|state	|string	|Only return pull requests that are in this state. This parameter can be repeated.|
### Values
* MERGED
* SUPERSEDED
* OPEN
* DECLINED

**Comment by charl** [comment]
Created https://github.com/ktrysmt/go-bitbucket/pull/62 as a stab at adding this.

**Comment by ktrysmt** [comment]
Thank you for your contribution! I will check it soon.
