### ISSUE TITLE
Create Branch & Push

### ISSUE THREAD

**Issue by ternblom** [ktrysmt/go-bitbucket#52]
Hello,

Is there a way to create a new branch using this library¿? and after make some changes, make a push ¿?

I already check and it is possible to commit but can't find how to do what I have been mentioned before.

Regards

**Comment by ktrysmt** [comment]
Hi, thank you for your contribution. @ternblom 

'go-bitbucket' is a small project. Therefore, there are no particular contribution rules. So you do not mind having them. You would send pull requests directly.

Would I tell you how to use github...

At first you would fork from "ktrysmt/go-bitbucket" to "ternblom/go-bitbucket".
Next commit your codes to "ternblom/go-bitbucket" with any branch name, and push it.
Finally create a pull-request to push "New pull request" button on <https://github.com/ktrysmt/go-bitbucket/pulls>, and set "" as source, "" as dist too.

Please post a comment if you have any other questions.
