### ISSUE TITLE
buildPullRequestBody panics when attempting to build reviewers map

### ISSUE THREAD

**Issue by smehtaca** [ktrysmt/go-bitbucket#54]
Hello,
Ran into a bug when attempting to update a pull request's reviewers.

**Description**

The buildPullRequestBody function has a panic while attempting to build a map for the reviewers for the body of the payload. This error occurs due to the way type assertion is used on line 96 of pull requests.go. 

Currently the code for building the reviewers map is as follows: 
```
	if n := len(po.Reviewers); n > 0 {
		for i, user := range po.Reviewers {
			body["reviewers"].([]map[string]string)[i] = map[string]string{"username": user}
		}
	}
```

**Resolution**

I managed to resolve the panic by not using type assertion, here is my fix:
```
	var reviewers []map[string]string
	if n := len(po.Reviewers); n > 0 {
		for _, user := range po.Reviewers {
			reviewer := map[string]string{"username": user}
			reviewers = append(reviewers, reviewer)
		}
		body["reviewers"] = reviewers
	}
```
Please let me know your thoughts on this proposed change or if you'd like me to create a PR for this.

Cheers!

**Comment by ktrysmt** [comment]
Hi, @smehtaca. Thank you for report it.

It would maybe wrong type assertion like you showed.
Could you like to create the pull request for it?

**Comment by smehtaca** [comment]
Hi @ktrysmt, 

My apologies, I had assumed the panic was caused by the type assertion. However, after further debugging it turns out the code was correct in the first place and looked faulty to my novice eyes. I can't seem to replicate the scenario that caused the panic so I will close this issue.

Once again, my apologies.

**Comment by ktrysmt** [comment]
@smehtaca 
I understood, don't worry about it. And I could not take the time to debug, so I am sorry too.
