### ISSUE TITLE
Missing error check leads to loss of error messages

### ISSUE THREAD

**Issue by soupdiver** [ktrysmt/go-bitbucket#56]
See: https://github.com/ktrysmt/go-bitbucket/blob/master/client.go#L150
The returned `err` is never checked.

Execution continues in error case and error information are lost.

**Comment by ktrysmt** [comment]
@soupdiver 
If returned `err` in the `execute()`, the caller object (e.x: repository.go#L89) will get `err` as the second argument.
And returned objects are checked immediately.

https://github.com/ktrysmt/go-bitbucket/blob/master/repository.go#L89-L92

If there is still something wrong, please teach me that. m(_ _)m

**Comment by soupdiver** [comment]
@ktrysmt The link is wrong since master has been updated.
https://github.com/ktrysmt/go-bitbucket/blob/master/client.go#L169

```
	c.authenticateRequest(req)
	result, err := c.doRequest(req, false)

	//autopaginate.
	resultMap, isMap := result.(map[string]interface{})
```

The `err` returned by `doRequest` is not handled

**Comment by ktrysmt** [comment]
Oh, I see, and understand it. I will fix it. Thank you. @soupdiver
