### ISSUE TITLE
You might want to revert PR (#58)

### ISSUE THREAD

**Issue by davidji99** [ktrysmt/go-bitbucket#60]
https://github.com/ktrysmt/go-bitbucket/pull/58 was rebased against my fork's `master` branch so it picked up a ton of potentially breaking changes rather than just having @mjpitz changes:
![Screen Shot 2019-05-31 at 18 13 01](https://user-images.githubusercontent.com/3991975/58695209-bfbfd580-83cf-11e9-9447-7073fa6014cd.png)

I suggest your revert (#58) from your repository and ask @mjpitz (if she still wants) to cherry pick her commits from (#58) to a new PR that's based from https://github.com/ktrysmt/go-bitbucket/commit/1f1c5e77687102cc8f6baa9f79276178be6f0ea3.

**Comment by davidji99** [comment]
Also, your `master` branch's `README.md now points to my fork as a result of that PR merge.

**Comment by mjpitz** [comment]
+1 to reverting my changes. I don't mind cherry picking them for this project if needed.

**Comment by ktrysmt** [comment]
Oops, thx. I understood, I will do it. @davidji99

**Comment by ktrysmt** [comment]
done! https://github.com/ktrysmt/go-bitbucket/pull/61

**Comment by davidji99** [comment]
👍
