### ISSUE TITLE
Add querying/filtering

### ISSUE THREAD

**Issue by charl** [ktrysmt/go-bitbucket#63]
This is somewhat related to https://github.com/ktrysmt/go-bitbucket/issues/38.

Having [querying/filtering](https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering) options (in my case specifically for pull requests) would be useful.

**Comment by charl** [comment]
Looked into this.

It's going to be a lot of work for someone to add generalised querying/filtering to this lib.

I'm going to add something specific for my needs to https://github.com/charl/go-bitbucket.

Feel free to backlog/close this one.

**Comment by charl** [comment]
In my [implementation](https://github.com/charl/go-bitbucket/blob/master/pullrequests.go#L27) of this I chose to push the assembly of the query/sort string on to the consumer of this lib.

**Comment by ktrysmt** [comment]
Fixed it by https://github.com/ktrysmt/go-bitbucket/commit/85aa0d8f96e2f8495fd32e95d8dea3b116dcd798.
