### ISSUE TITLE
json.Unmarshal() throws error while GetDiff() between 2 commits of 2 branches

### ISSUE THREAD

**Issue by Vicky000** [ktrysmt/go-bitbucket#82]
While I call GetDiff() to get diff of 2 branches, I fed it with a `&DiffOptions{Owner:"myOwner", RepoSlug:"myRepo", Spec: "364bb0..7cfdc3"} `
, 364bb0 is the last commitId of branch1 and 7cfdc3 is the last commitId of branch2. [Refer to the usage of {spec} in atlassian doc [https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/diff/%7Bspec%7D]]

Error occurred while parse response body into interface{} in client.go
`       var result interface{}
	err = json.Unmarshal(resBodyBytes, &result)
`
err: invalid character 'd' looking for beginning of value

Not sure if here needs an enhancement, because the return is a []uint8 type of a plain string not with a JSON struct like "{a:x, y:b}".

**Comment by Vicky000** [comment]
Sorry, close this issue, byte is the alias for uint8, the error above was my bad.

**Comment by Vicky000** [comment]
this issue should be duplicated with #29.

**Comment by ktrysmt** [comment]
Oops sorry I will check it asap. @Vicky000

**Comment by ktrysmt** [comment]
I fixed by https://github.com/ktrysmt/go-bitbucket/pull/84. 

Please see the sample(test) code: https://github.com/ktrysmt/go-bitbucket/blob/master/tests/diff_test.go#L28-L37
