### ISSUE TITLE
Posting PR comments

### ISSUE THREAD

**Issue by Trane9991** [ktrysmt/go-bitbucket#87]
I found the code for reading comments, however, I couldn't find functionality for posting comments.
Is it planned?

Thanks!

**Comment by ktrysmt** [comment]
I see. It was not planned until now, I will do it in future.

**Comment by btsteve** [comment]
I was just looking for the same thing.

**Comment by leodamasceno** [comment]
+1

**Comment by btsteve** [comment]
I am willing to help but i am still a novice at go.
